spring.application.name=goods-gateway
server.port=9000

mybatis.configuration.map-underscore-to-camel-case=true
eureka.client.service-url.defaultZone=http://localhost:8000/eureka/

zuul.routes.goods-list.path=/list/**
zuul.routes.goods.service-id=goods
zuul.routes.order.path=/order/**
zuul.routes.order.service-id=order